[tool.poetry]
name = "pycounts_jchang"
version = "0.1.0"
description = "Count words in a file."
authors = ["Jenson Chang"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
